import { MediaType } from "@models/media.model"
import { ExternalMovie } from "./models/media-details.model"

export const movieData: ExternalMovie[] = [
  {
    mediaType: MediaType.MOVIE,
    directors: ["Denis Villeneuve"],
    genre: ["Sci-Fi", "Adventure"],
    duration: 165,
    title: "Dune 2",
    imageUrl: "https://image.tmdb.org/t/p/w1280/dM2eC02Dq3iMtBZZDFtXSLHfFKJ.jpg",
    description: "Le voyage mythique de Paul Atreides qui s'allie à Chani et aux Fremen dans sa quête de vengeance envers les conspirateurs qui ont anéanti sa famille. Devant choisir entre l'amour de sa vie et le destin de l'univers, il fera tout pour éviter un terrible futur que lui seul peut prédire.",
    releaseDate: "28/02/2024",
  },
  {
    mediaType: MediaType.MOVIE,
    directors: ["Richard Kelly"],
    genre: ["Sci-Fi", "Psychological", "Drama"],
    duration: 113,
    title: "Donnie Darko",
    imageUrl: "https://www.themoviedb.org/t/p/w1280/z3gIuT4e4tjCKYEYJChcBI44U21.jpg",
    description: "A troubled teenager experiences disturbing visions that lead him to question time, fate, and reality.",
    releaseDate: "26/10/2001",
  },
  {
    mediaType: MediaType.MOVIE,
    directors: ["David Fincher"],
    genre: ["Drama"],
    duration: 139,
    title: "Fight Club",
    imageUrl: "https://www.themoviedb.org/t/p/w1280/t1i10ptOivG4hV7erkX3tmKpiqm.jpg",
    description: "Un employé de bureau insomniaque...",
    releaseDate: "15/10/1999",
  },
  {
    mediaType: MediaType.MOVIE,
    directors: ["Ridley Scott"],
    genre: ["Sci-Fi", "Horror", "Thriller"],
    duration: 117,
    title: "Alien",
    imageUrl: "https://www.themoviedb.org/t/p/w1280/l8CES84JndFlNfBNMxdLRYaLvI6.jpg",
    description: "The crew of a commercial spaceship encounters a deadly extraterrestrial lifeform.",
    releaseDate: "25/05/1979",
  },
  {
    mediaType: MediaType.MOVIE,
    directors: ["Christopher Nolan"],
    genre: ["Sci-Fi", "Adventure", "Drama"],
    duration: 169,
    title: "Interstellar",
    imageUrl: "https://www.themoviedb.org/t/p/w1280/1pnigkWWy8W032o9TKDneBa3eVK.jpg",
    description: "A team of explorers travels through a wormhole in space to ensure humanity’s survival.",
    releaseDate: "07/11/2014",
  },
  {
    mediaType: MediaType.MOVIE,
    directors: ["Daniel Kwan", "Daniel Scheinert"],
    genre: ["Comedy", "Sci-Fi", "Drama"],
    duration: 139,
    title: "Everything Everywhere All at Once",
    imageUrl: "https://www.themoviedb.org/t/p/w1280/qHy7BlA1I3iUEIGp7atsMjSNJSK.jpg",
    description: "Evelyn Wang est à bout...",
    releaseDate: "25/03/2022",
  },
  {
    mediaType: MediaType.MOVIE,
    directors: ["Danny Boyle"],
    genre: ["Horror", "Thriller", "Sci-Fi"],
    duration: 113,
    title: "28 Days Later",
    imageUrl: "https://www.themoviedb.org/t/p/w1280/y0u77LC6C0UvhiWe4LiI2KulHN9.jpg",
    description: "A virus outbreak devastates the UK...",
    releaseDate: "01/11/2002",
  },
  {
    mediaType: MediaType.MOVIE,
    directors: ["Ridley Scott"],
    genre: ["Sci-Fi", "Thriller", "Drama"],
    duration: 117,
    title: "Blade Runner",
    imageUrl: "https://www.themoviedb.org/t/p/w1280/zHKWxyG4j404HVeSYHNH4niUpkW.jpg",
    description: "A detective hunts rogue androids in a dystopian future.",
    releaseDate: "25/06/1982",
  },
  {
    mediaType: MediaType.MOVIE,
    directors: ["Neill Blomkamp"],
    genre: ["Sci-Fi", "Action", "Drama"],
    duration: 112,
    title: "District 9",
    imageUrl: "https://www.themoviedb.org/t/p/w1280/gW7H7GPIWSEG7Ma7KKRCx9BfJQm.jpg",
    description: "Aliens are segregated in a slum on Earth...",
    releaseDate: "14/08/2009",
  },
  {
    mediaType: MediaType.MOVIE,
    directors: ["Christopher Nolan"],
    genre: ["Action", "Sci-Fi", "Thriller"],
    duration: 150,
    title: "Tenet",
    imageUrl: "https://www.themoviedb.org/t/p/w1280/72SOtZnFhCumLRZhoXlX8g2IkgF.jpg",
    description: "A secret agent manipulates time...",
    releaseDate: "26/08/2020",
  },
  {
    mediaType: MediaType.MOVIE,
    directors: ["Bong Joon-ho"],
    genre: ["Sci-Fi", "Action", "Drama"],
    duration: 126,
    title: "Snowpiercer",
    imageUrl: "https://www.themoviedb.org/t/p/w1280/vRr9z33hkI0Hp1gCCtV6s1jbf9.jpg",
    description: "Survivors of a new ice age live on a train...",
    releaseDate: "01/08/2013",
  },
  {
    mediaType: MediaType.MOVIE,
    directors: ["Damien Chazelle"],
    genre: ["Romance", "Drama", "Musical"],
    duration: 128,
    title: "La La Land",
    imageUrl: "https://www.themoviedb.org/t/p/w1280/5KIj6aioW1UtUT1IV0qqW5iZbNH.jpg",
    description: "A musician and an actress fall in love...",
    releaseDate: "09/12/2016",
  },
  {
    mediaType: MediaType.MOVIE,
    directors: ["Hayao Miyazaki"],
    genre: ["Animation", "Family", "Fantasy"],
    duration: 86,
    title: "My Neighbor Totoro",
    imageUrl: "https://www.themoviedb.org/t/p/w1280/eEpy8IiR8N0S6mgkdAjDCMlMYQO.jpg",
    description: "Two girls discover magical forest spirits...",
    releaseDate: "16/04/1988",
  },
  {
    mediaType: MediaType.MOVIE,
    directors: ["Jérémie Périn"],
    genre: ["Sci-Fi", "Adventure", "Drama"],
    duration: 85,
    title: "Mars Express",
    imageUrl: "https://www.themoviedb.org/t/p/w1280/JEPbbxkFtRASU1WzeQGRvKqjuO.jpg",
    description: "En l’an 2200...",
    releaseDate: "22/11/2023",
  },
  {
    mediaType: MediaType.MOVIE,
    directors: ["Katsuhiro Otomo"],
    genre: ["Animation", "Sci-Fi", "Action"],
    duration: 124,
    title: "Akira",
    imageUrl: "https://www.themoviedb.org/t/p/w1280/8fCn7TwTe0Z4fTugIiLssX6UcHe.jpg",
    description: "In post-apocalyptic Neo-Tokyo...",
    releaseDate: "16/07/1988",
  },
  {
    mediaType: MediaType.MOVIE,
    directors: ["Hayao Miyazaki"],
    genre: ["Animation", "Adventure", "Fantasy"],
    duration: 117,
    title: "Nausicaä of the Valley of the Wind",
    imageUrl: "https://www.themoviedb.org/t/p/w1280/sIcv6IiaL6Ad2KGUOdRyJHIZpgC.jpg",
    description: "A princess fights to save a toxic world...",
    releaseDate: "11/03/1984",
  }
]
